### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Ge6ben/dynamic-form#2]
I think you meant `filterField`

https://github.com/Ge6ben/dynamic-form/blob/501e59fb2643e2aa3ee980b6d224d7cffef0e0ce/src/components/dynamic-form/field-wrapper.vue#L20

**Comment by Ge6ben** [comment]
Oops kindly make a commit if u possible @sschneider-ihre-pvs

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
i am on it, don't worry @sschneider-ihre-pvs  @Ge6ben

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
pull request opened

**Comment by Ge6ben** [comment]
Merged in this [PR](https://github.com/Ge6ben/dynamic-form/pull/3/commits/f87eac1741fdb57aa82865e643e8665349ac7817)
Thanks Guys
